import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { fetchEvents } from './eventsAPI';

const initialState = {
    events: [],
    status: 'idle',
    error: null
};

export const getEventsAsync = createAsyncThunk(
    'events/fetchEvents',
    async (url) => {
        const response = await fetchEvents(url);
        return response;
    }
);

export const eventsSlice = createSlice({
    name: 'events',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {},
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
      builder
        .addCase(getEventsAsync.pending, (state) => {
          state.status = 'loading';
        })
        .addCase(getEventsAsync.rejected, (state) => {
          state.status = 'failed';
          state.error = "Sorry, There was an error retrieveing repositories for this organization."
        })
        .addCase(getEventsAsync.fulfilled, (state, action) => {

          if(Array.isArray(action.payload)){
            state.status = 'successful';
            state.events.push(...action.payload);
          } else {
            state.status = 'failed';
            state.error = action.payload.message
          }
        });
    },
});

export const allEvents = (state) => state.events.events;
export const allEventsStatus = (state) => state.events.status;
export const allEventsError = (state) => state.events.error;

export default eventsSlice.reducer;