import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { fetchRepositories } from './repositoriesAPI';

const initialState = {
    repositories: [],
    status: 'idle',
    error: null
};

export const getRepositoriesAsync = createAsyncThunk(
    'repositories/fetchRepositories',
    async (url) => {
        const response = await fetchRepositories(url);
        return response;
    }
);

export const repositoriesSlice = createSlice({
    name: 'repositories',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {},
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
      builder
        .addCase(getRepositoriesAsync.pending, (state) => {
          state.status = 'loading';
        })
        .addCase(getRepositoriesAsync.rejected, (state) => {
          state.status = 'failed';
          state.error = "Sorry, There was an error retrieveing repositories for this organization."
        })
        .addCase(getRepositoriesAsync.fulfilled, (state, action) => {
          if(Array.isArray(action.payload)){
            state.status = 'successful';
            state.repositories.push(...action.payload);
          } else {
            state.status = 'failed';
            state.error = action.payload.message
          }
        });
    },
});

export const allRepositories = (state) => state.repositories.repositories;
export const allRepositoriesStatus = (state) => state.repositories.status;
export const allRepositoriesError = (state) => state.repositories.error;

export default repositoriesSlice.reducer;